config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :events
  resource :shopping_cart
  resources :payments
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/has_reference.rb
module HasReference

  extend ActiveSupport::Concern

  module ClassMethods

    def generate_reference
      loop do
        result = SecureRandom.hex(10)
        return result unless exists?(reference: result)
      end
    end

  end

end

app/models/event.rb
class Event < ApplicationRecord

  has_many :performances, dependent: :destroy

end

app/models/payment.rb
class Payment < ActiveRecord::Base

  include HasReference

  belongs_to :user, optional:true
  has_many :payment_line_items
  has_many :tickets, through: :payment_line_items,
                     source_type: "Ticket", source: "buyable"

  monetize :price_cents

  enum status: [:created, :succeeded]

  def total_cost
    tickets.map(&:price).sum
  end

  def create_line_items(tickets)
    tickets.each do |ticket|
      payment_line_items.create!(
        buyable: ticket, price_cents: ticket.price.cents)
    end
  end

end

app/models/payment_line_item.rb
class PaymentLineItem < ApplicationRecord
  belongs_to :payment
  belongs_to :buyable, polymorphic: true

  monetize :price_cents
end

app/models/performance.rb
class Performance < ApplicationRecord
  belongs_to :event
  has_many :tickets

  def unsold_tickets(count)
    tickets.where(status: "unsold").limit(count)
  end
end

app/models/shopping_cart.rb
class ShoppingCart

  attr_accessor :user

  def initialize(user)
    @user = user
  end

  def tickets
    @tickets ||= user.tickets_in_cart
  end

  def events
    tickets.map(&:event).uniq.sort_by(&:name)
  end

  def tickets_by_performance
    tickets.group_by { |t| t.performance.id }
  end

  def performance_count
    tickets_by_performance.each_pair.each_with_object({}) do |pair, result|
      result[pair.first] = pair.last.size
    end
  end

  def performances_for(event)
    tickets.map(&:performance)
        .select { |performance| performance.event == event }
        .uniq.sort_by(&:start_time)
  end

  def subtotal_for(performance)
    tickets_by_performance[performance.id].sum(&:price)
  end

  def total_cost
    tickets.map(&:price).sum
  end

end

app/models/stripe_charge.rb
class StripeCharge

  attr_accessor :token, :payment, :response

  def self.charge(token:, payment:)
    StripeCharge.new(token: token, payment: payment).charge
  end

  def initialize(token:, payment:)
    @token = token
    @payment = payment
  end

  def charge
    return if response.present?
    @response = Stripe::Charge.create(
      {amount: payment.price.cents, currency: "usd",
        source: token.id, description: "",
        metadata: {reference: payment.reference}},
        idempotency_key: payment.reference)
  end

end

app/models/stripe_token.rb
class StripeToken

  attr_accessor :credit_card_number, :expiration_month, :expiration_year, :cvc, :stripe_token

  def initialize(credit_card_number: nil, expiration_month: nil, expiration_year: nil, cvc: nil, stripe_token: nil)
    @credit_card_number = credit_card_number
    @expiration_month = expiration_month
    @expiration_year = expiration_year
    @cvc = cvc
    @stripe_token = stripe_token
  end

  def token
    @token ||= (stripe_token ? retrieve_token : create_token)
  end

  def id
    stripe_token || token.id
  end
  
  private def retrieve_token
    Stripe::Token.retrieve(stripe_token)
  end

  private def create_token
    Stripe::Token.create(
        card: {number: credit_card_number, exp_month: expiration_month,
               exp_year: expiration_year, cvc: cvc})
  end

  def to_s
    "STRIPE TOKEN: #{id}"
  end

  def inspect
    "STRIPE TOKEN #{id}"
  end

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :performance
  has_one :event, through: :performance
  monetize :price_cents

  enum status: {unsold: 0, waiting: 1, purchased: 2}
  enum access: {general: 0}

  def place_in_cart_for(user)
    update(status: :waiting, user: user)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: {user: 0, vip: 1, admin: 2}
  
  has_many :tickets

  def tickets_in_cart
    tickets.waiting.all.to_a
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def show
    @payment = Payment.find_by(reference: params[:id])
  end

  def create
    token = StripeToken.new(**card_params)
    workflow = PurchasesCart.new(
      user: current_user, stripe_token: token,
      purchase_amount_cents: params[:purchase_amount_cents])
    workflow.run
    if workflow.success
      redirect_to payment_path(id: workflow.payment.reference)
    else
      redirect_to shopping_cart_path
    end
  end

  private def card_params
    params.permit(
      :credit_card_number, :expiration_month,
      :expiration_year, :cvc,
      :stripe_token).to_h.symbolize_keys
  end

end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController

  def show
    @cart = ShoppingCart.new(current_user)
  end

  def update
    performance = Performance.find(params[:performance_id])
    workflow = AddsToCart.new(
        user: current_user, performance: performance,
        count: params[:ticket_count])
    workflow.run
    if workflow.success
      redirect_to shopping_cart_path
    else
      redirect_to performance.event
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.slim
h2 Upcoming Performances
- @events.each do |event|
  h2= link_to(event.name, event_path(event))

app/views/events/show.html.slim
h1= @event.name

h2 Available Performances
- @event.performances.each do |performance|
  div(id=dom_id(performance))
    .row
      = form_tag(shopping_cart_path, method: :patch) do
        = hidden_field_tag("performance_id", performance.id)
        .col-md-2
          h4= performance.start_time.to_date.to_s(:long)
        .col-md-1
          .form-group
            = select_tag("ticket_count",
                options_for_select((1..10).to_a), class: "form-control")
        .col-md-3
          .form-group
            = submit_tag("Add to Cart",
                class: "btn btn-primary", id: "add-to-cart")

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      button.navbar-toggle(
        data-target=".navbar-collapse" data-toggle="collapse")
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
    = link_to("Snow Globe Theater", root_path, class: "navbar-brand")
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        = render "layouts/navigation_links"

app/views/layouts/_navigation_links.html.slim
li= link_to("Events", events_path)
- if user_signed_in?
  li= link_to("Edit account", edit_user_registration_path)
  li= link_to("Sign out", destroy_user_session_path, method: "delete")
- else
  li= link_to("Sign in", new_user_session_path)
  li= link_to("Sign up", new_user_registration_path)

app/views/layouts/application.html.slim
doctype html
html(lang="en")
  head
    meta(charset="utf-8")
    meta(name="viewport" content="width=device-width, initial-scale=1.0")
    title= content_for?(:title) ? yield(:title) : "Snow Globe Theater"
    meta(name="description"
      content="#{content_for?(:description) ? yield(:description) : "Globe"}")
    / START: code.add_stripe
    = stylesheet_link_tag("application",
      media: "all", "data-turbolinks-track" => true)
    = javascript_include_tag("#{STRIPE_JS_HOST}/v2/#{STRIPE_JS_FILE}")
    = javascript_include_tag("application", "data-turbolinks-track" => true)

    javascript:
      Stripe.setPublishableKey(
        "#{Rails.application.secrets.stripe_publishable_key}");
    /END: code.add_stripe

    = stylesheet_link_tag("application",
      media: "all", "data-turbolinks-track" => true)
    = javascript_include_tag("#{STRIPE_JS_HOST}/v2/#{STRIPE_JS_FILE}")
    = csrf_meta_tags

  body
    header
      = render "layouts/navigation"
    main(role="main")
      .container
        = render "layouts/messages"
        = yield

app/views/payments/show.html.slim
h1 Payment Number: #{@payment.reference}

table.table
  thead
    tr
      th Ticket #
      th Event
      th Date
      th Price
    tbody
      - @payment.payment_line_items.each do |payment_line_item|
        - ticket = payment_line_item.buyable
        tr.purchased_ticket(id=dom_id(ticket, :purchased))
          td= ticket.reference
          td= ticket.event.name
          td= ticket.performance.start_time.to_date.to_s(:long)
          td.subtotal= humanized_money_with_symbol(payment_line_item.price)

h3 Total #{humanized_money_with_symbol(@payment.total_cost)}

app/views/shopping_carts/show.html.slim
h1 Shopping Cart

- @cart.events.each do |event|
  h2= event.name
  div(id=dom_id(event))
    table.table
      thead
        th Date
        th Tickets
        th Total Price
      tbody
        - @cart.performances_for(event).each do |performance|
          tr(id=dom_id(performance))
            td= performance.start_time.to_date.to_s(:long)
            td.ticket_count= @cart.performance_count[performance.id]
            td.subtotal
              = humanized_money_with_symbol(@cart.subtotal_for(performance))

h3 Total #{humanized_money_with_symbol(@cart.total_cost)}
//#
h2 Checkout

h3 Credit Card Info

= form_tag(payments_path, class: "form-inline") do
  = hidden_field_tag(:purchase_amount_cents, @cart.total_cost.cents)
  .row
    .form_group
      = label_tag(:credit_card_number, "Credit Card Number", class: "sr-only")
      input.form-control(placeholder="Credit Card #"
        data-stripe="number" id="credit_card_number")

    .form_group
      = label_tag(:expiration_month, "Month", class: "sr-only")
      input.form-control(placeholder="Month"
        data-stripe="exp-month" id="expiration_month")

      = label_tag(:expiration_year, "Year", class: "sr-only")
      input.form-control(placeholder="Year"
        data-stripe="exp-year" id="expiration_year")

      = label_tag(:cvc, "Year", class: "sr-only")
      input.form-control(placeholder="CVC #" data-stripe="cvc" id="cvc")
  .row
    .form_group
      = submit_tag("Purchase Cart", class: "btn btn-default", id: "purchase")
//#

app/views/visitors/index.html.erb
<h3>Welcome</h3>